name: Cypress E2E     # workflow name

on:
  pull_request:
  push:
    branches: [ main ]   # ensures main always has the latest result

jobs:
  cypress-e2e:
    name: cypress-e2e    # the check-run name
    runs-on: ubuntu-latest
    timeout-minutes: 15  # avoid hanging jobs
    
    env:
      # Basic environment variables for testing
      NODE_ENV: test
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
      # Mock environment variables for tests
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:54321
      NEXT_PUBLIC_SUPABASE_ANON_KEY: test-key
      BEEHIIV_API_TOKEN: test-token
      BEEHIIV_PUBLICATION_ID: test-pub-id
      
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      # Install dependencies with pnpm
      - run: pnpm install --frozen-lockfile
      
      # Build the application
      - run: pnpm build

      # Start the production server in background
      - run: pnpm start -- --port 3000 &
      
      # Wait for server to be ready with longer timeout
      - run: npx wait-on http://localhost:3000 --timeout 60000
      
      # Verify server is responding
      - run: curl -f http://localhost:3000 || (echo "Server not responding" && exit 1)

      # Run Cypress tests
      - run: pnpm cy:run
      
      # Upload screenshots and videos on failure
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 7 